# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://drummantra3030.com
title: Drummantra3030
email: richstitzelmusic@gmail.com
author: Matt Cordier
description: > # "Write an awesome description for your new site here. 
  Rich Stitzel Music Presents The Drummantra 3030. 
  Over 15 hours of guided exercises to improve your Time, Feel, and Confidence on the drums. 
copyright: 'Copyright &copy; 2018 Rich Stitzel Music. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: public/_scss
  style: compressed

plugins:
  - octopress-autoprefixer

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/richstitzelmusic
  - title: twitter
    url: https://twitter.com/richstitzel
  - title: instagram
    url: https://www.instagram.com/richstitzelmusic/
  - title: google plus
    url: https://plus.google.com/u/0/+richstitzel
  - title: youtube
    url: https://www.youtube.com/thedrummantra
  - title: vimeo
    url: https://vimeo.com/user33449918     
